# Generated by Django 2.1.5 on 2022-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('city', models.TextField(default='Moscow')),
            ],
        ),
    ]
