# Generated by Django 2.1.5 on 2022-12-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=models.TextField(blank=True, null=True),
        ),
    ]
